export const UI_KEY_DOWN = 'UI_KEY_DOWN'

export const SYS_GAME_START = 'SYS_GAME_START'
export const SYS_GAME_OVER = 'SYS_GAME_OVER'
export const SYS_GAME_MOVE = 'SYS_GAME_MOVE'
export const SYS_GAME_EAT = 'SYS_GAME_EAT'

export const SET_PLAYING = 'SET_PLAYING'
export const SET_BOARD = 'SET_BOARD'
export const SET_PLAYER = 'SET_PLAYER'
export const SET_PLAYER_POINT = 'SET_PLAYER_POINT'
export const SET_PLAYER_DIRECTION = 'SET_PLAYER_DIRECTION'
export const SET_PLAYER_LENGTH = 'SET_PLAYER_LENGTH'
